CREATE TABLE IF NOT EXISTS COMPANY_TYPE (
    COMPANY_TYPE_ID bigint NOT NULL,
    COMPANY_TYPE_NAME varchar(100) NOT NULL,
    PRIMARY KEY (COMPANY_TYPE_ID)
);

CREATE TABLE IF NOT EXISTS COMPANY_LOCATION (
    COMPANY_LOCATION_ID bigint NOT NULL,
    COMPANY_LOCATION_NAME varchar(100) NOT NULL,
    PRIMARY KEY (COMPANY_LOCATION_ID)
);

CREATE TABLE IF NOT EXISTS MEMBER (
    MEMBER_ID bigint NOT NULL AUTO_INCREMENT,
    COMPANY_TYPE_ID bigint NOT NULL,
    COMPANY_LOCATION_ID bigint NOT NULL,
    NAME varchar(100) NOT NULL,
    PASSWORD varchar(100) NOT NULL,
    SEX varchar(10) NOT NULL,
    COMPANY_NAME varchar(100) NOT NULL,
    PRIMARY KEY (MEMBER_ID),
    FOREIGN KEY (COMPANY_TYPE_ID) REFERENCES COMPANY_TYPE(COMPANY_TYPE_ID),
    FOREIGN KEY (COMPANY_LOCATION_ID) REFERENCES COMPANY_LOCATION(COMPANY_LOCATION_ID)
);